name: Rspec Tests

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        ruby: [ 2.3, 2.4, 2.5, 2.6, 2.7 ]
    name: rspec for ${{ matrix.ruby }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
    
      - name: Implement gem caching
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install bundle
        run: |
          gem install bundler -v '<2.0'
          bundle config path vendor/bundle
          bundle config set without 'staging production'
          bundle install --jobs 4 --retry 3

      - name: Run rspec tests
        run: bundle exec rspec
        
      # - name: Undercover
      #   run: |
      #     git remote set-branches --add origin master
      #     git fetch
      #     bundle exec undercover -c origin/master
                  
